baseURL = "/blog/"
publishDir = ".."

# https://github.com/josephhutch/aether
theme = "hugo-theme-myhugo"

languageCode = "en-us"
title = "Andrew's Blog"

googleAnalytics = "UA-107434487-3"

[params]
description = "Musings of my life"
bgImg = "IMG_0072.jpg"
brandImg = "logo.png"
brand = "andrew wong"

[[menu.main]]
  name = "blog"
  url = "_blog_"
[[menu.main]]
  name = "about me"
  url = "/about"
[[menu.main]]
  name = "photography"
  url = "/photos"
[[menu.main]]
  name = "programming"
  url = "/programming"

