baseURL = ""
publishDir = ".."

relativeurls = true

# https://github.com/josephhutch/aether
theme = "aether"

languageCode = "en-us"
title = "Andrew's Blog"

googleAnalytics = "UA-107434487-3"

[params]
brand = "[Back to Home]"
description = "Musings of my life"
# homeimg = "../greyHome.jng"
bgimg = "IMG_0072.jpg"

# Enable Chroma
pygmentsCodeFences = true
pygmentsUseClasses = true
