name: deploy sapper to github pages

on: push

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v1
      with:
        node-version: '14.9.0'


    - name: Install packages
      run: yarn

    - name: Build
      run: yarn export

    - name: Set CNAME
      run: echo featherbear.cc > ./__sapper__/export/CNAME

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./__sapper__/export
