name: deploy site to github pages

on:
  push:
    branches:
    - v3.1

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '23.6.1'

    - uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Install packages
      run: pnpm install --frozen-lockfile
    
    - name: Install scripts packages
      run: |
        cd scripts
        pnpm install --frozen-lockfile --dangerously-allow-all-builds

    - name: Build
      run: pnpm run build

    - name: Generate PDFs
      run: pnpm run export:pdf

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: build

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
