name: deploy site to github pages

on: push

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v1
      with:
        node-version: '14.9.0'

    - name: Install packages
      run: yarn
    
    - name: Install scripts packages
      run: |
        cd scripts
        yarn

        # https://github.com/actions/virtual-environments/issues/710#issuecomment-612869886
        sudo fc-match "Noto Color Emoji" || sudo apt-get install fonts-noto-color-emoji -y
        mkdir -p /usr/local/share/fonts
        cp /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf /usr/local/share/fonts/
        chmod 644 /usr/local/share/fonts/NotoColorEmoji.ttf

        fc-cache -fv

    - name: Build
      run: yarn export

    - name: Generate PDFs
      run: yarn export:pdf

    - name: Set CNAME
      run: echo featherbear.cc > ./__sapper__/export/CNAME

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./__sapper__/export
