name: deploy site to github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v1
      with:
        node-version: '14.9.0'

    - name: Install packages
      run: yarn
    
    - name: Install scripts packages
      run: |
        cd scripts
        yarn

    - name: Build
      run: yarn export

    - name: Generate PDFs
      run: yarn export:pdf

    - name: Set CNAME
      run: echo featherbear.cc > ./__sapper__/export/CNAME

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./__sapper__/export
